# Generated by Django 4.1.7 on 2023-04-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='ini default deskripsi produk detail'),
            preserve_default=False,
        ),
    ]
