# Generated by Django 4.1.7 on 2023-04-05 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 5, 22, 12, 43, 398273, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
