# Generated by Django 4.1.7 on 2023-04-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trasaction_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
